export const POPUP_INTERVAL_STORAGE_KEY = "POPUP_INTERVAL_STORAGE_KEY";
export const POPUP_POSITION_STORAGE_KEY = "POPUP_POSITION_STORAGE_KEY";
export const POPUP_SCREEN_TIME_STORAGE_KEY = "POPUP_SCREEN_TIME_STORAGE_KEY";
